from ..caret_tracker import _CARET_MARKER
from ..buffer import VirtualBuffer
from ..indexer import text_to_virtual_buffer_tokens
from ...utils.test import create_test_suite

def test_remove_selecting_single_tokens(assertion):
    vb = VirtualBuffer()
    vb.insert_tokens(text_to_virtual_buffer_tokens("Insert a new sentence. \n", "insert a new sentence"))
    vb.insert_tokens(text_to_virtual_buffer_tokens("Insert a second sentence. \n", "insert a second sentence"))
    vb.insert_tokens(text_to_virtual_buffer_tokens("Insert a third sentence.", "insert a third sentence"))
    vb.caret_tracker.text_buffer = """Insert a new sentence. 
Insert a second """ + _CARET_MARKER + """sentence. 
Insert a third sentence."""

    assertion( "    Selecting a single character to the left and remove it...")
    vb.apply_key("shift:down left shift:up backspace")
    assertion( "        Expect token length to stay the same (3)", len(vb.tokens) == 3)
    caret_index = vb.caret_tracker.get_caret_index() 
    assertion( "        Expect caret line index to be 1", caret_index[0] == 1)
    assertion( "        Expect caret character index to be the same as before (10)", caret_index[1] == 10)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[1].text == "Insert a secondsentence. \n")
    assertion( "        Expect phrase to be merged", vb.tokens[1].phrase == "insert a secondsentence")
    assertion( "    Selecting three characters to the right and remove them...")
    vb.apply_key("shift:down right:3 shift:up delete")
    assertion( "        Expect token length to stay the same (3)", len(vb.tokens) == 3)
    caret_index = vb.caret_tracker.get_caret_index() 
    assertion( "        Expect caret line index to be 1", caret_index[0] == 1)
    assertion( "        Expect caret character index to be the three less than before (7)", caret_index[1] == 7)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[1].text == "Insert a secondtence. \n")
    assertion( "        Expect phrase to be merged", vb.tokens[1].phrase == "insert a secondtence")
    assertion( "    Selecting right beyond the line break and remove the selection...")
    vb.apply_key("shift:down right:10 shift:up backspace")
    assertion( "        Expect token length to be one less (2)", len(vb.tokens) == 2)
    caret_index = vb.caret_tracker.get_caret_index()
    assertion( "        Expect caret line index to be 1", caret_index[0] == 1)
    assertion( "        Expect caret character index to be the start of the next sentence (22)", caret_index[1] == 22)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[1].text == "Insert a secondsert a third sentence.")
    assertion( "        Expect phrase to be merged", vb.tokens[1].phrase == "insert a secondsert a third sentence")
    assertion( "    Selecting left beyond the line break and remove the selection...")
    vb.apply_key("shift:down left:18 shift:up backspace")
    assertion( "        Expect token length to be one less (1)", len(vb.tokens) == 1)
    caret_index = vb.caret_tracker.get_caret_index()
    assertion( "        Expect caret line index to be 0", caret_index[0] == 0)
    assertion( "        Expect caret character index to be the end of the sentence (22)", caret_index[1] == 22)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[0].text == "Insert a new sentencesert a third sentence.")
    assertion( "        Expect phrase to be merged", vb.tokens[0].phrase == "insert a new sentencesert a third sentence")

def test_remove_selecting_multiple_tokens_left(assertion):
    vb = VirtualBuffer()
    vb.insert_tokens(text_to_virtual_buffer_tokens("Suggest", "suggest"))
    vb.insert_tokens(text_to_virtual_buffer_tokens(" create", "create"))
    vb.insert_tokens(text_to_virtual_buffer_tokens(" delete", "delete"))
    vb.insert_tokens(text_to_virtual_buffer_tokens(" insertion", "insertion"))
    vb.caret_tracker.text_buffer = "Suggest create delete insert" + _CARET_MARKER + "ion"

    assertion( "    Selecting characters until the left side of the token is reached and removing it...")
    vb.apply_key("shift:down left:7 shift:up backspace")
    assertion( "        Expect token length to be one less (3)", len(vb.tokens) == 3)
    caret_index = vb.caret_tracker.get_caret_index()
    assertion( "        Expect caret line index to be 0", caret_index[0] == 0)
    assertion( "        Expect caret character index to be the same as before (3)", caret_index[1] == 3)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[-1].text == " deleteion")
    assertion( "        Expect phrase to be merged", vb.tokens[-1].phrase == "deleteion")
    assertion( "    Selecting characters until multiple tokens have been skipped over and removing it...")
    vb.apply_key("shift:down left:14 shift:up backspace")
    assertion( "        Expect token length to be two less (1)", len(vb.tokens) == 1)
    caret_index = vb.caret_tracker.get_caret_index()
    assertion( "        Expect caret line index to be 0", caret_index[0] == 0)
    assertion( "        Expect caret character index to be the same as before (3)", caret_index[1] == 3)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[-1].text == "Suggestion")
    assertion( "        Expect phrase to be merged", vb.tokens[-1].phrase == "suggestion")

def test_remove_selecting_multiple_tokens_right(assertion):
    vb = VirtualBuffer()
    vb.insert_tokens(text_to_virtual_buffer_tokens("Suggest ", "suggest"))
    vb.insert_tokens(text_to_virtual_buffer_tokens("create ", "create"))
    vb.insert_tokens(text_to_virtual_buffer_tokens("delete ", "delete"))
    vb.insert_tokens(text_to_virtual_buffer_tokens("insertion", "insertion"))
    vb.caret_tracker.text_buffer = "Suggest" + _CARET_MARKER + " create delete insertion"

    assertion( "With a filled virtual buffer")
    assertion( "    Selecting characters until the right side of the token is reached and removing it...")
    vb.apply_key("shift:down right shift:up backspace")
    assertion( "        Expect token length to be one less (3)", len(vb.tokens) == 3)
    caret_index = vb.caret_tracker.get_caret_index() 
    assertion( "        Expect caret line index to be 0", caret_index[0] == 0)
    assertion( "        Expect caret character index to be one less than before same as before (23)", caret_index[1] == 23)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[0].text == "Suggestcreate ")
    assertion( "        Expect phrase to be merged", vb.tokens[0].phrase == "suggestcreate")
    assertion( "    Selecting characters until multiple tokens have been skipped over and removing it...")
    vb.apply_key("shift:down right:20 shift:up backspace")
    assertion( "        Expect token length to be two less (1)", len(vb.tokens) == 1)
    caret_index = vb.caret_tracker.get_caret_index()
    assertion( "        Expect caret line index to be 0", caret_index[0] == 0)
    assertion( "        Expect caret character index to be 20 less than before (3)", caret_index[1] == 3)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[-1].text == "Suggestion")
    assertion( "        Expect phrase to be merged", vb.tokens[-1].phrase == "suggestion")

suite = create_test_suite("Removing selected text")
suite.add_test(test_remove_selecting_single_tokens)
suite.add_test(test_remove_selecting_multiple_tokens_left)
suite.add_test(test_remove_selecting_multiple_tokens_right)