from ..caret_tracker import _CARET_MARKER
from ..buffer import VirtualBuffer
from ..indexer import text_to_virtual_buffer_tokens
from ...utils.test import create_test_suite

def test_single_token_replacement(assertion):
    vb = VirtualBuffer()
    vb.insert_tokens(text_to_virtual_buffer_tokens("Insert a new sentence. \n", "insert a new sentence"))
    vb.insert_tokens(text_to_virtual_buffer_tokens("Insert a second sentence. \n", "insert a second sentence"))
    vb.insert_tokens(text_to_virtual_buffer_tokens("Insert a third sentence.", "insert a third sentence"))
    vb.caret_tracker.text_buffer = """Insert a new sentence. 
Insert a second """ + _CARET_MARKER + """sentence. 
Insert a third sentence."""

    assertion( "    Selecting a single character to the left and replace it...")
    vb.apply_key("shift:down left shift:up")
    vb.insert_tokens(text_to_virtual_buffer_tokens("G"))
    assertion( "        Expect buffer length to stay the same (3)", len(vb.tokens) == 3)
    caret_index = vb.caret_tracker.get_caret_index() 
    assertion( "        Expect caret line index to be 1", caret_index[0] == 1)
    assertion( "        Expect caret character index to be the same as before (10)", caret_index[1] == 10)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[1].text == "Insert a secondGsentence. \n")
    assertion( "        Expect phrase to be merged", vb.tokens[1].phrase == "insert a secondgsentence")
    assertion( "    Selecting a single character to the right and replace it...")
    vb.apply_key("shift-right")
    vb.insert_tokens(text_to_virtual_buffer_tokens("G"))
    assertion( "        Expect buffer length to stay the same (3)", len(vb.tokens) == 3)
    caret_index = vb.caret_tracker.get_caret_index()
    assertion( "        Expect caret line index to be 1", caret_index[0] == 1)
    assertion( "        Expect caret character index to be one more than before (9)", caret_index[1] == 9)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[1].text == "Insert a secondGGentence. \n")
    assertion( "        Expect phrase to be merged", vb.tokens[1].phrase == "insert a secondggentence")
    assertion( "    Selecting right beyond the line break and replace the selection...")
    vb.apply_key("left shift-right:11")
    vb.insert_tokens(text_to_virtual_buffer_tokens(" and "))
    assertion( "        Expect buffer length to be the one more than before (4)", len(vb.tokens) == 4)
    caret_index = vb.caret_tracker.get_caret_index()
    assertion( "        Expect caret line index to be 1", caret_index[0] == 1)
    assertion( "        Expect caret character index to be the start of the next sentence (24)", caret_index[1] == 24)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "    Selecting left beyond the line break and replace the selection...")
    vb.apply_key("shift:down left:5 left:18 shift:up")
    vb.insert_tokens(text_to_virtual_buffer_tokens("But also... "))
    assertion( "        Expect buffer length to be the one less than before (3)", len(vb.tokens) == 3)
    caret_index = vb.caret_tracker.get_caret_index()
    assertion( "        Expect caret line index to be 0", caret_index[0] == 0)
    assertion( "        Expect caret character index to be the middle of the joined sentence (24)", caret_index[1] == 24)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)

def test_multiple_token_replacement_left(assertion):
    vb = VirtualBuffer()
    vb.insert_tokens(text_to_virtual_buffer_tokens("Suggest", "suggest"))
    vb.insert_tokens(text_to_virtual_buffer_tokens(" create", "create"))
    vb.insert_tokens(text_to_virtual_buffer_tokens(" delete", "delete"))
    vb.insert_tokens(text_to_virtual_buffer_tokens(" insertion", "insertion"))
    vb.caret_tracker.text_buffer = "Suggest create delete insert" + _CARET_MARKER + "ion"

    assertion( "    Selecting characters until the left side of the token is reached and replacing it...")
    vb.apply_key("shift-left:7")
    vb.insert_tokens(text_to_virtual_buffer_tokens("rat"))
    assertion( "        Expect buffer length to be one less (3)", len(vb.tokens) == 3)
    caret_index = vb.caret_tracker.get_caret_index()
    assertion( "        Expect caret line index to be 0", caret_index[0] == 0) 
    assertion( "        Expect caret character index to be the same as before (3)", caret_index[1] == 3)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[-1].text == " deleteration")
    assertion( "        Expect phrase to be merged", vb.tokens[-1].phrase == "deleteration")
    assertion( "    Selecting characters until multiple tokens have been skipped over and replacing it...")
    vb.apply_key("shift:down left:17 shift:up") 
    vb.insert_tokens(text_to_virtual_buffer_tokens("ilat"))
    assertion( "        Expect buffer length to be two less (1)", len(vb.tokens) == 1)
    caret_index = vb.caret_tracker.get_caret_index() 
    assertion( "        Expect caret line index to be 0", caret_index[0] == 0)
    assertion( "        Expect caret character index to be the same as before (3)", caret_index[1] == 3)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[-1].text == "Suggestilation")
    assertion( "        Expect phrase to be merged", vb.tokens[-1].phrase == "suggestilation")

def test_multiple_token_replacement_right(assertion):
    vb = VirtualBuffer()
    vb.insert_tokens(text_to_virtual_buffer_tokens("Suggest ", "suggest"))
    vb.insert_tokens(text_to_virtual_buffer_tokens("create ", "create"))
    vb.insert_tokens(text_to_virtual_buffer_tokens("delete ", "delete"))
    vb.insert_tokens(text_to_virtual_buffer_tokens("insertion", "insertion"))
    vb.caret_tracker.text_buffer = "Suggest" + _CARET_MARKER + " create delete insertion"

    assertion( "    Selecting characters until the right side of the token is reached and replacing it...")
    vb.apply_key("shift-right")
    vb.insert_tokens(text_to_virtual_buffer_tokens("or"))
    assertion( "        Expect buffer length to be one less (3)", len(vb.tokens) == 3)
    caret_index = vb.caret_tracker.get_caret_index()
    assertion( "        Expect caret line index to be 0", caret_index[0] == 0)
    assertion( "        Expect caret character index to be the same as before (23)", caret_index[1] == 23)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[0].text == "Suggestorcreate ")
    assertion( "        Expect phrase to be merged", vb.tokens[0].phrase == "suggestorcreate")
    assertion( "    Selecting characters until multiple tokens have been skipped over and replacing it...")
    vb.apply_key("shift:down right:20 shift:up")
    vb.insert_tokens(text_to_virtual_buffer_tokens("in"))
    assertion( "        Expect buffer length to be two less (1)", len(vb.tokens) == 1)
    caret_index = vb.caret_tracker.get_caret_index()
    assertion( "        Expect caret line index to be 0", caret_index[0] == 0)
    assertion( "        Expect caret character index to be 20 less than before (3)", caret_index[1] == 3)
    assertion( "        Expect no selection detected", vb.is_selecting() == False)
    assertion( "        Expect text to be merged", vb.tokens[-1].text == "Suggestorinion")
    assertion( "        Expect phrase to be merged", vb.tokens[-1].phrase == "suggestorinion")

suite = create_test_suite("Replacing selection with new text")
suite.add_test(test_single_token_replacement)
suite.add_test(test_multiple_token_replacement_left)
suite.add_test(test_multiple_token_replacement_right)