from ..input_fixer import InputFixer

def get_input_fixer():
    return InputFixer("en", "test", None)

input_fixer = get_input_fixer()
print( "Using an empty input fixer")
print( "    Inserting 'want too make'...")
text = input_fixer.automatic_fix("too", "want", "make")
print( "        Should not change the text automatically because it has no fixes", text == "too")
print( "    Adding a single fix for 'want too make' and inserting it again...")
input_fixer.add_fix("too", "to", "want", "make")
text = input_fixer.automatic_fix("too", "want", "make")
print( "        Should change the text automatically because the automatic fixes are persisted", text == "to")
print( "    Inserting 'want too make' again should give 'want to make'")
text = input_fixer.automatic_fix("too", "want", "make")
print( "        Should change the text automatically", text == "to")

input_fixer = get_input_fixer()
print( "Using an input fixer with the word 'period' as a known no-context fix to be '.'")
input_fixer.add_fix("period", ".", "", "", 6)
print( "    Inserting 'a period of'...")
text = input_fixer.automatic_fix("period", "a", "of")
print( "        Should change the text automatically because the zero-context fix is to change period to .", text == ".")
print( "    Adding a single fix for 'a . of' and inserting it again...")
input_fixer.add_fix(".", "period", "a", "of")
text = input_fixer.automatic_fix("period", "a", "of")
print( "        Should change the text automatically because the automatic fixes with more context are persisted", text == "period")
print( "    Inserting 'a period that'...")
text = input_fixer.automatic_fix("period", "a", "that")
print( "         Should also keep the word 'period' because it has matching previous context...", text == "period")
print( "    Inserting 'the period of'...")
text = input_fixer.automatic_fix("period", "the", "of")
print( "         Should also keep the word 'period' because it has matching next context...", text == "period")
print( "    Inserting 'birds period and'...")
text = input_fixer.automatic_fix("period", "birds", "and")
print( "         Should keep using . as a fix because no known fixes have been made with the given context", text == ".")