from ..input_history import InputHistoryManager
from ...utils.test import create_test_suite

def exact_cursor_navigation(assertion):
    input_history = InputHistoryManager()
    input_history.insert_input_events(input_history.text_to_input_history_events("Insert ", "insert"))
    input_history.insert_input_events(input_history.text_to_input_history_events("a ", "a"))
    input_history.insert_input_events(input_history.text_to_input_history_events("new ", "new"))
    input_history.insert_input_events(input_history.text_to_input_history_events("word.", "word"))

    assertion( "Navigating between input events on a single line")
    assertion( "    Navigating to the end of the first event...")
    keys = input_history.go_phrase("insert")
    assertion( "        Expect history length to stay the same (4)", len(input_history.input_history) == 4)
    cursor_index = input_history.cursor_position_tracker.get_cursor_index()
    assertion( "        Expect cursor line index to be 0", cursor_index[0] == 0)
    assertion( "        Expect cursor character index to be the end of the first word", cursor_index[1] == 11)
    assertion( "    Navigating to the start of the first event...") 
    keys = input_history.go_phrase("insert", "start") 
    assertion( "        Expect left to be pressed 7 times", keys[0] == "left:7")
    cursor_index = input_history.cursor_position_tracker.get_cursor_index()
    assertion( "        Expect cursor line index to be 0", cursor_index[0] == 0)
    assertion( "        Expect cursor character index to be the start of the first word", cursor_index[1] == 18)
    assertion( "    Navigating to the start of the third event...")
    keys = input_history.go_phrase("new", "start")
    assertion( "        Expect right to be pressed 9 times", keys[0] == "right:9")
    cursor_index = input_history.cursor_position_tracker.get_cursor_index() 
    assertion( "        Expect cursor line index to be 0", cursor_index[0] == 0)
    assertion( "        Expect cursor character index to be the start of the third word", cursor_index[1] == 9)
    assertion( "    Navigating to the end of the last event...") 
    keys = input_history.go_phrase("word", "end")
    assertion( "        Expect right to be pressed 9 times", keys[0] == "right:9")
    cursor_index = input_history.cursor_position_tracker.get_cursor_index() 
    assertion( "        Expect cursor line index to be 0", cursor_index[0] == 0)
    assertion( "        Expect cursor character index to be the end of the sentence", cursor_index[1] == 0)
    assertion( "    Navigating to a non-existing event...") 
    keys = input_history.go_phrase("bee", "end")
    assertion( "        Expect no keys to be pressed", keys is None)
    cursor_index = input_history.cursor_position_tracker.get_cursor_index() 
    assertion( "        Expect cursor index to be the same", cursor_index == (0, 0))

    input_history.insert_input_events(input_history.text_to_input_history_events("\n", ""))
    input_history.insert_input_events(input_history.text_to_input_history_events("Append ", "append"))
    input_history.insert_input_events(input_history.text_to_input_history_events("a ", "a"))
    input_history.insert_input_events(input_history.text_to_input_history_events("new ", "new"))
    input_history.insert_input_events(input_history.text_to_input_history_events("sentence.", "sentence"))
    input_history.insert_input_events(input_history.text_to_input_history_events("\n", ""))
    input_history.insert_input_events(input_history.text_to_input_history_events("Add ", "add"))
    input_history.insert_input_events(input_history.text_to_input_history_events("a ", "a"))
    input_history.insert_input_events(input_history.text_to_input_history_events("final ", "final"))
    input_history.insert_input_events(input_history.text_to_input_history_events("line.", "line"))
    assertion( "Navigating between input events on multiple lines")
    assertion( "    Navigating to the end of the second sentence...")
    keys = input_history.go_phrase("sentence") 
    assertion( "        Expect up to be pressed once", "up" in keys)
    assertion( "        Expect end to be pressed at least once", "end" in keys)
    cursor_index = input_history.cursor_position_tracker.get_cursor_index()
    assertion( "        Expect cursor line index to be 1", cursor_index[0] == 1)
    assertion( "        Expect cursor character index to be the end of the sentence", cursor_index[1] == 0)
    assertion( "    Navigating to the end of the final sentence...")
    keys = input_history.go_phrase("line")
    assertion( "        Expect down to be pressed once", "down" in keys)
    assertion( "        Expect end to be pressed at least once", "end" in keys)
    cursor_index = input_history.cursor_position_tracker.get_cursor_index()
    assertion( "        Expect cursor line index to be 2", cursor_index[0] == 2)
    assertion( "        Expect cursor character index to be the end of the sentence", cursor_index[1] == 0)
    assertion( "    Navigating to the end of the first event...")   
    keys = input_history.go_phrase("insert")
    assertion( "        Expect up to be pressed two times", "up:2" in keys)
    assertion( "        Expect end to be pressed at least once", "end" in keys)
    cursor_index = input_history.cursor_position_tracker.get_cursor_index()
    assertion( "        Expect cursor line index to be 0", cursor_index[0] == 0)
    assertion( "        Expect cursor character index to be the end of the first word", cursor_index[1] == 11)
    assertion( "    Navigating to the end of the third word on the final sentence...")
    keys = input_history.go_phrase("final")
    cursor_index = input_history.cursor_position_tracker.get_cursor_index()
    assertion( "        Expect down to be pressed two times", "down:2" in keys)
    assertion( "        Expect end to be pressed at least once", "end" in keys)
    assertion( "        Expect cursor line index to be 2", cursor_index[0] == 2)
    assertion( "        Expect cursor character index to be the end of the third word", cursor_index[1] == 5)
    assertion( "    Navigating to a non-existing event...") 
    keys = input_history.go_phrase("bee", "end")
    assertion( "        Expect no keys to be pressed", keys is None)
    cursor_index = input_history.cursor_position_tracker.get_cursor_index()  
    assertion( "        Expect cursor index to be the same", cursor_index == (2, 5))

suite = create_test_suite("Exact cursor navigation")
suite.add_test(exact_cursor_navigation)