from ..input_history import InputHistoryManager
from ...utils.test import create_test_suite

def get_filled_ihm():
    ihm = InputHistoryManager()
    ihm.insert_input_events(ihm.text_to_input_history_events("Insert ", "insert"))
    ihm.insert_input_events(ihm.text_to_input_history_events("a ", "a"))
    ihm.insert_input_events(ihm.text_to_input_history_events("new ", "new"))
    ihm.insert_input_events(ihm.text_to_input_history_events("sentence, ", "sentence"))
    ihm.insert_input_events(ihm.text_to_input_history_events("that ", "that"))
    ihm.insert_input_events(ihm.text_to_input_history_events("will ", "will"))
    ihm.insert_input_events(ihm.text_to_input_history_events("have ", "have"))
    ihm.insert_input_events(ihm.text_to_input_history_events("new ", "new"))
    ihm.insert_input_events(ihm.text_to_input_history_events("words ", "words"))
    ihm.insert_input_events(ihm.text_to_input_history_events("compared ", "compared"))
    ihm.insert_input_events(ihm.text_to_input_history_events("to ", "to"))
    ihm.insert_input_events(ihm.text_to_input_history_events("the ", "the"))
    ihm.insert_input_events(ihm.text_to_input_history_events("previous ", "previous"))
    ihm.insert_input_events(ihm.text_to_input_history_events("sentence.", "sentence"))
    return ihm

def test_looping_sentence(assertion):
    input_history = get_filled_ihm()
    assertion( "    Moving from the end to the history to the last occurrence of 'sentence'...") 
    keys = input_history.go_phrase("sentence", 'start')
    assertion( "        Should go left until the last occurrence of sentence", keys[0] == "left:9")
    assertion( "    Repeating the search for 'sentence'...") 
    keys = input_history.go_phrase("sentence", 'start')
    assertion( "        Should go left until the first occurrence of sentence", keys[0] == "left:60")
    assertion( "    Repeating the search for 'sentence' again...") 
    keys = input_history.go_phrase("sentence", 'start')
    assertion( "        Should loop back to the last occurrence", keys[0] == "right:60")
    assertion( "    Repeating the search for 'sentence' once more...")
    keys = input_history.go_phrase("sentence", 'start')
    assertion( "        Should loop back to the first occurrence", keys[0] == "left:60")

    input_history = get_filled_ihm()
    assertion( "    Moving from the end to the history to the last occurrence of 'sentence'...") 
    keys = input_history.go_phrase("sentence", 'end')
    assertion( "        Should not move anywhere as we are already at the end", len(keys) == 0)
    assertion( "    Repeating the search for 'sentence'...")
    keys = input_history.go_phrase("sentence", 'end')
    assertion( "        Should go left until the first occurrence of sentence", keys[0] == "left:59")
    assertion( "    Repeating the search for 'sentence' again...")
    keys = input_history.go_phrase("sentence", 'end')
    assertion( "        Should loop back to the last occurrence", keys[0] == "right:59")
    assertion( "    Repeating the search for 'sentence' once more...")
    keys = input_history.go_phrase("sentence", 'end')
    assertion( "        Should loop back to the first occurrence", keys[0] == "left:59")

def test_looping_new_sentence(assertion):
    input_history = get_filled_ihm()
    assertion( "    Moving from the end to the history to the last occurrence of 'new'...") 
    keys = input_history.go_phrase("new", 'end')
    assertion( "        Should move to the left until we have reached the word new", keys[0] == "left:40")
    assertion( "    Searching for 'sentence'...")
    keys = input_history.go_phrase("sentence", 'end')
    assertion( "        Should go left until the first occurrence of sentence, because it comes before the current cursor", keys[0] == "left:19")
    assertion( "    Repeating the search for 'sentence' again...")
    keys = input_history.go_phrase("sentence", 'end')
    assertion( "        Should loop back to the last occurrence", keys[0] == "right:59")

def test_looping_to(assertion):
    input_history = get_filled_ihm()
    assertion( "    Moving from the end to the history to the last occurrence of 'to'...") 
    keys = input_history.go_phrase("to", 'end')
    assertion( "        Should move to the left until we have reached the word 'to'", keys[0] == "left:22")
    assertion( "    Repeating the search for 'to' again...")
    keys = input_history.go_phrase("to", 'end')
    assertion( "        Should not move the cursor as there is only one option", len(keys) == 0)

def test_looping_new(assertion):
    input_history = get_filled_ihm()
    assertion( "Using a filled input history which contains duplicates of certain words")
    assertion( "    Moving from the end to the history to selecting the first occurrence of 'new'...") 
    keys = input_history.select_phrase("new")
    assertion( "        Should move to the left until we have reached the word 'new'", keys[0] == "left:44")
    assertion( "        Should move to the right until we have reached the end of the word 'new'", keys[2] == "right:4")
    assertion( "    Repeating the search for 'new' again...")
    keys = input_history.select_phrase("new")
    assertion( "        Should move to the left until we have reached the second occurrence", keys[1] == "left:29")
    assertion( "        Should move to the right until we have reached the end of the word 'new'", keys[3] == "right:4")

suite = create_test_suite("Using a filled input history which contains duplicates of certain words")
suite.add_test(test_looping_sentence)
suite.add_test(test_looping_new_sentence)
suite.add_test(test_looping_to)
suite.add_test(test_looping_new)