from ..cursor_position_tracker import CursorPositionTracker, _CURSOR_MARKER
from ..input_history import InputHistoryManager
from ..input_history_typing import InputHistoryEvent

input_history = InputHistoryManager()
input_history.insert_input_events(input_history.text_to_input_history_events("Insert a new sentence. \n", "insert a new sentence"))
input_history.insert_input_events(input_history.text_to_input_history_events("Insert a second sentence. \n", "insert a second sentence"))
input_history.insert_input_events(input_history.text_to_input_history_events("Insert a third sentence.", "insert a third sentence"))
input_history.cursor_position_tracker.text_history = """Insert a new sentence. 
Insert a second """ + _CURSOR_MARKER + """sentence. 
Insert a third sentence."""

print( "With a filled input history")
print( "    Selecting a single character to the left and replace it...")
input_history.apply_key("shift:down left shift:up")
input_history.insert_input_events(input_history.text_to_input_history_events("G"))
print( "        Expect history length to stay the same (3)", len(input_history.input_history) == 3)
cursor_index = input_history.cursor_position_tracker.get_cursor_index() 
print( "        Expect cursor line index to be 1", cursor_index[0] == 1)
print( "        Expect cursor character index to be the same as before (10)", cursor_index[1] == 10)
print( "        Expect no selection detected", input_history.is_selecting() == False)
print( "        Expect text to be merged", input_history.input_history[1].text == "Insert a secondGsentence. \n")
print( "        Expect phrase to be merged", input_history.input_history[1].phrase == "insert a secondgsentence")
print( "    Selecting a single character to the right and replace it...")
input_history.apply_key("shift:down right shift:up")
input_history.insert_input_events(input_history.text_to_input_history_events("G"))
print( "        Expect history length to stay the same (3)", len(input_history.input_history) == 3)
cursor_index = input_history.cursor_position_tracker.get_cursor_index()
print( "        Expect cursor line index to be 1", cursor_index[0] == 1)
print( "        Expect cursor character index to be one more than before (9)", cursor_index[1] == 9)
print( "        Expect no selection detected", input_history.is_selecting() == False)
print( "        Expect text to be merged", input_history.input_history[1].text == "Insert a secondGGentence. \n")
print( "        Expect phrase to be merged", input_history.input_history[1].phrase == "insert a secondggentence")
print( "    Selecting right beyond the line break and replace the selection...")
input_history.apply_key("left shift:down right:11 shift:up")
input_history.insert_input_events(input_history.text_to_input_history_events(" and "))
print( "        Expect history length to be the one more than before (4)", len(input_history.input_history) == 4)
cursor_index = input_history.cursor_position_tracker.get_cursor_index()
print( "        Expect cursor line index to be 1", cursor_index[0] == 1)
print( "        Expect cursor character index to be the start of the next sentence (24)", cursor_index[1] == 24)
print( "        Expect no selection detected", input_history.is_selecting() == False)
print( "    Selecting left beyond the line break and replace the selection...")
input_history.apply_key("shift:down left:5 left:17 shift:up")
input_history.insert_input_events(input_history.text_to_input_history_events("But also... "))
print( "        Expect history length to be the one less than before (3)", len(input_history.input_history) == 3)
cursor_index = input_history.cursor_position_tracker.get_cursor_index()
print( "        Expect cursor line index to be 0", cursor_index[0] == 0)
print( "        Expect cursor character index to be the middle of the joined sentence (24)", cursor_index[1] == 24)
print( "        Expect no selection detected", input_history.is_selecting() == False)

input_history = InputHistoryManager()
input_history.insert_input_events(input_history.text_to_input_history_events("Suggest", "suggest"))
input_history.insert_input_events(input_history.text_to_input_history_events(" create", "create"))
input_history.insert_input_events(input_history.text_to_input_history_events(" delete", "delete"))
input_history.insert_input_events(input_history.text_to_input_history_events(" insertion", "insertion"))
input_history.cursor_position_tracker.text_history = "Suggest create delete insert" + _CURSOR_MARKER + "ion"

print( "With a filled input history")
print( "    Selecting characters until the left side of the event is reached and replacing it...")
input_history.apply_key("shift:down left:7 shift:up")
input_history.insert_input_events(input_history.text_to_input_history_events("rat"))
print( "        Expect history length to be one less (3)", len(input_history.input_history) == 3)
cursor_index = input_history.cursor_position_tracker.get_cursor_index()
print( "        Expect cursor line index to be 0", cursor_index[0] == 0) 
print( "        Expect cursor character index to be the same as before (3)", cursor_index[1] == 3)
print( "        Expect no selection detected", input_history.is_selecting() == False)
print( "        Expect text to be merged", input_history.input_history[-1].text == " deleteration")
print( "        Expect phrase to be merged", input_history.input_history[-1].phrase == "deleteration")
print( "    Selecting characters until multiple events have been skipped over and replacing it...")
input_history.apply_key("shift:down left:17 shift:up") 
input_history.insert_input_events(input_history.text_to_input_history_events("ilat"))
print( "        Expect history length to be two less (1)", len(input_history.input_history) == 1)
cursor_index = input_history.cursor_position_tracker.get_cursor_index() 
print( "        Expect cursor line index to be 0", cursor_index[0] == 0)
print( "        Expect cursor character index to be the same as before (3)", cursor_index[1] == 3)
print( "        Expect no selection detected", input_history.is_selecting() == False)
print( "        Expect text to be merged", input_history.input_history[-1].text == "Suggestilation")
print( "        Expect phrase to be merged", input_history.input_history[-1].phrase == "suggestilation")

input_history = InputHistoryManager()
input_history.insert_input_events(input_history.text_to_input_history_events("Suggest ", "suggest"))
input_history.insert_input_events(input_history.text_to_input_history_events("create ", "create"))
input_history.insert_input_events(input_history.text_to_input_history_events("delete ", "delete"))
input_history.insert_input_events(input_history.text_to_input_history_events("insertion", "insertion"))
input_history.cursor_position_tracker.text_history = "Suggest" + _CURSOR_MARKER + " create delete insertion"
print( "With a filled input history")
print( "    Selecting characters until the right side of the event is reached and replacing it...")
input_history.apply_key("shift:down right shift:up")
input_history.insert_input_events(input_history.text_to_input_history_events("or"))
print( "        Expect history length to be one less (3)", len(input_history.input_history) == 3)
cursor_index = input_history.cursor_position_tracker.get_cursor_index()
print( "        Expect cursor line index to be 0", cursor_index[0] == 0)
print( "        Expect cursor character index to be the same as before (23)", cursor_index[1] == 23)
print( "        Expect no selection detected", input_history.is_selecting() == False)
print( "        Expect text to be merged", input_history.input_history[0].text == "Suggestorcreate ")
print( "        Expect phrase to be merged", input_history.input_history[0].phrase == "suggestorcreate")
print( "    Selecting characters until multiple events have been skipped over and replacing it...")
input_history.apply_key("shift:down right:20 shift:up")
input_history.insert_input_events(input_history.text_to_input_history_events("in"))
print( "        Expect history length to be two less (1)", len(input_history.input_history) == 1)
cursor_index = input_history.cursor_position_tracker.get_cursor_index()
print( "        Expect cursor line index to be 0", cursor_index[0] == 0)
print( "        Expect cursor character index to be 20 less than before (3)", cursor_index[1] == 3)
print( "        Expect no selection detected", input_history.is_selecting() == False)
print( "        Expect text to be merged", input_history.input_history[-1].text == "Suggestorinion")
print( "        Expect phrase to be merged", input_history.input_history[-1].phrase == "suggestorinion")