from ..input_history import InputHistoryManager
from ...utils.test import create_test_suite

def test_select_single_word_and_extending(assertion):
    input_history = InputHistoryManager()
    input_history.insert_input_events(input_history.text_to_input_history_events("Insert ", "insert"))
    input_history.insert_input_events(input_history.text_to_input_history_events("a ", "a"))
    input_history.insert_input_events(input_history.text_to_input_history_events("new ", "new"))
    input_history.insert_input_events(input_history.text_to_input_history_events("sentence.", "sentence"))

    assertion( "    Selecting a single character to the left and then selecting 'Insert a'...")
    input_history.apply_key("shift:down left shift:up")
    input_history.select_phrase("insert")
    keys = input_history.select_phrase("a", True)
    assertion( "        Should have the text 'Insert a ' selected", input_history.cursor_position_tracker.get_selection_text() == 'Insert a ')
    assertion( "        Should not deselect the previous selection", keys[0] not in ["left", "right"])
    assertion( "        Should go right 2 times to connect the end of 'Insert ' with 'a '", keys[1] == "right:2")
    assertion( "    Deselecting, and then selecting 'Insert ' until 'new ' after that...")
    input_history.select_phrase("insert")
    keys = input_history.select_phrase("new", True)
    assertion( "        Should have the text 'Insert a new ' selected", input_history.cursor_position_tracker.get_selection_text() == 'Insert a new ')
    assertion( "        Should not deselect the previous selection", keys[0] not in ["left", "right"])
    assertion( "        Should go right 6 times to connect the end of 'Insert ' with 'new '", keys[1] == "right:6") 
    assertion( "    Selecting 'Insert ' and extend it until the end of the history...")
    keys = input_history.select_until_end("insert")
    assertion( "        Should have the text 'Insert a new sentence.' selected", input_history.cursor_position_tracker.get_selection_text() == 'Insert a new sentence.')
    assertion( "        Should deselect the previous selection", keys[0] in ["left", "right"])
    assertion( "        Should hold down shift before moving the cursor again", keys[1] == "shift:down")
    assertion( "        Should go right 22 times to connect the end of 'Insert ' with 'sentence.'", keys[2] == "right:22")
    assertion( "    Selecting 'new ' and extend it until the end of the history...")
    input_history.select_phrase("new")
    keys = input_history.select_until_end()
    assertion( "        Should have the text 'new sentence.' selected", input_history.cursor_position_tracker.get_selection_text() == 'new sentence.')
    assertion( "        Should not deselect the previous selection", keys[0] not in ["left", "right"])
    assertion( "        Should hold down shift before moving the cursor again", keys[0] == "shift:down")
    assertion( "        Should go right 9 times to connect the end of 'new ' with 'sentence.'", keys[1] == "right:9")
    assertion( "    Selecting 'Insert ' using 'inssert' and extend it until the end of the history...")
    keys = input_history.select_until_end("inssert")
    assertion( "        Should have the text 'Insert a new sentence.' selected", input_history.cursor_position_tracker.get_selection_text() == 'Insert a new sentence.')
    assertion( "        Should deselect the previous selection", keys[0] in ["left", "right"])
    assertion( "        Should hold down shift before moving the cursor again", keys[2] == "shift:down")
    assertion( "        Should go right 22 times to connect the end of 'Insert ' with 'sentence.'", keys[3] == "right:22")

def test_selecting_multiple_phrases_with_duplicates(assertion):
    input_history = InputHistoryManager()
    input_history.insert_input_events(input_history.text_to_input_history_events("Insert ", "insert"))
    input_history.insert_input_events(input_history.text_to_input_history_events("a ", "a"))
    input_history.insert_input_events(input_history.text_to_input_history_events("new ", "new"))
    input_history.insert_input_events(input_history.text_to_input_history_events("sentence ", "sentence"))
    input_history.insert_input_events(input_history.text_to_input_history_events("or ", "or"))
    input_history.insert_input_events(input_history.text_to_input_history_events("insert ", "insert"))
    input_history.insert_input_events(input_history.text_to_input_history_events("a ", "a"))
    input_history.insert_input_events(input_history.text_to_input_history_events("new ", "new"))
    input_history.insert_input_events(input_history.text_to_input_history_events("paragraph.", "paragraph"))
    assertion( "    Selecting a single character to the left and then selecting 'insert a'...")
    input_history.apply_key("shift:down left shift:up")
    input_history.select_phrase("insert")
    keys = input_history.select_phrase("a", True)
    assertion( "        Should have the text 'insert a ' selected", input_history.cursor_position_tracker.get_selection_text() == 'insert a ')
    assertion( "        Should not deselect the previous selection", keys[0] not in ["left", "right"])
    assertion( "        Should go right 2 times to connect the end of 'insert ' with 'a '", keys[1] == "right:2")
    assertion( "    Selecting 'Insert ' by selecting 'insert' again, and then selecting 'a'...")
    input_history.select_phrase("insert")
    input_history.select_phrase("insert")
    keys = input_history.select_phrase("a", True)
    assertion( "        Should have the text 'Insert a ' selected", input_history.cursor_position_tracker.get_selection_text() == 'Insert a ')
    assertion( "        Should not deselect the previous selection", keys[0] not in ["left", "right"])
    assertion( "        Should hold down shift before moving the cursor again", keys[0] == "shift:down")
    assertion( "        Should go right 2 times to connect the end of 'Insert ' with 'a ' beside it", keys[1] == "right:2")
    assertion( "    Selecting 'Insert a new ' by continuing the selection with 'new'...")
    keys = input_history.select_phrase("new", True)
    assertion( "        Should have the text 'Insert a new ' selected", input_history.cursor_position_tracker.get_selection_text() == 'Insert a new ')
    assertion( "        Should not deselect the previous selection", keys[0] not in ["left", "right"])
    assertion( "        Should hold down shift before moving the cursor again", keys[0] == "shift:down")
    assertion( "        Should go right 4 times to connect the end of 'a ' with 'new ' beside it", keys[1] == "right:4")
    assertion( "    Selecting 'sentence or ' by starting the selection with 'or' and continuing it with 'sentence'...")
    input_history.select_phrase("or")
    keys = input_history.select_phrase("sentence", True)
    assertion( "        Should have the text 'sentence or ' selected", input_history.cursor_position_tracker.get_selection_text() == 'sentence or ')
    assertion( "        Should deselect the previous selection", keys[0] in ["left", "right"])
    assertion( "        Should move from the start of the previous selection to the beginning of the new selection", keys[1] == "left:9")
    assertion( "        Should then hold down shift", keys[2] == "shift:down")
    assertion( "        And then go right until the selection has been made", keys[3] == "right:12" )
    assertion( "    Selecting 'or ' by dragging the cursor left, and then adding 'sentence '...")
    input_history.select_phrase("or")
    input_history.apply_key("right shift:down left:3 shift:up")
    keys = input_history.select_phrase("sentence", True)
    assertion( "        Should have the text 'sentence or' selected", input_history.cursor_position_tracker.get_selection_text() == 'sentence or ')
    assertion( "        Should not deselect the previous selection", keys[0] not in ["left", "right"])
    assertion( "        Should move from the start of the previous selection to the beginning of the new selection", keys[1] == "left:9")
    assertion( "    Selecting 'or ' by dragging the cursor left, and then adding 'insert '...")
    input_history.select_phrase("or")
    input_history.apply_key("right shift:down left:3 shift:up")
    keys = input_history.select_phrase("insert", True)
    assertion( "        Should have the text 'or insert ' selected", input_history.cursor_position_tracker.get_selection_text() == 'or insert ')
    assertion( "        Should deselect the previous selection", keys[0] in ["left", "right"] )
    assertion( "        Should then hold down shift", keys[1] == "shift:down")
    assertion( "        And then should move from the start of the previous selection to the end of the new selection", keys[2] == "right:10")

def test_select_phrase_inside_selection_with_duplicates(assertion):
    input_history = InputHistoryManager()
    input_history.insert_input_events(input_history.text_to_input_history_events("Insert ", "insert"))
    input_history.insert_input_events(input_history.text_to_input_history_events("a ", "a"))
    input_history.insert_input_events(input_history.text_to_input_history_events("new ", "new"))
    input_history.insert_input_events(input_history.text_to_input_history_events("sentence ", "sentence"))
    input_history.insert_input_events(input_history.text_to_input_history_events("or ", "or"))
    input_history.insert_input_events(input_history.text_to_input_history_events("insert ", "insert"))
    input_history.insert_input_events(input_history.text_to_input_history_events("a ", "a"))
    input_history.insert_input_events(input_history.text_to_input_history_events("new ", "new"))
    input_history.insert_input_events(input_history.text_to_input_history_events("paragraph.", "paragraph"))
    assertion( "    Selecting 'or insert a ' and then selecting 'insert'...")
    input_history.select_phrase("or")
    input_history.select_phrase("insert", True)
    input_history.select_phrase("new", True)
    keys = input_history.select_phrase("insert")
    assertion( "        Should have the text 'insert ' selected", input_history.cursor_position_tracker.get_selection_text() == 'insert ')
    assertion( "        Should deselect the previous selection", keys[0] in ["left", "right"])
    assertion( "        Should go right 3 times to go to the start of 'insert'", keys[1] == "right:3")
    assertion( "        Should then hold down shift", keys[2] == "shift:down")
    assertion( "        And then go right until 'insert ' is selected", keys[3] == "right:7")

suite = create_test_suite("Selection range after words")
suite.add_test(test_select_single_word_and_extending)
suite.add_test(test_selecting_multiple_phrases_with_duplicates)
suite.add_test(test_select_phrase_inside_selection_with_duplicates)