from ..separator_formatter import SeparatorFormatter
from ..capitalization_formatter import CapitalizationFormatter, CAPITALIZATION_STRATEGY_ALL_CAPS, CAPITALIZATION_STRATEGY_LOWERCASE, CAPITALIZATION_STRATEGY_TITLECASE

dot_separator = SeparatorFormatter("dots", ".")
print( "Separator formatters" )
print( "    should not add the separator to single words", dot_separator.words_to_format(["This"]) == ["This"])
print( "    should add the separator after the first word", dot_separator.words_to_format(["This", "Thing"]) == ["This.", "Thing"])
print( "    should add the separator separately if the previous word lacks it", dot_separator.words_to_format(["This", "Thing"], "After") == [".", "This.", "Thing"])
print( "    should not add the separator if only one word is given", dot_separator.words_to_format(["This"], "After") == [".", "This"])

large_separator = SeparatorFormatter("large", "-=-")
print( "Multiple character separator formatters" )
print( "    should not add the separator to single words", large_separator.words_to_format(["This"]) == ["This"])
print( "    should add the separator after the first word", large_separator.words_to_format(["This", "Thing"]) == ["This-=-", "Thing"])
print( "    should add the separator separately if the previous word lacks it", large_separator.words_to_format(["This", "Thing"], "After") == ["-=-", "This-=-", "Thing"])
print( "    should not add the separator if only one word is given", large_separator.words_to_format(["This"], "After") == ["-=-", "This"])

lowercase_formatter = CapitalizationFormatter("lower", " ")
print( "Lower case formatter with separators" )
print( "    should keep lower case words the same", lowercase_formatter.words_to_format(["this"]) == ["this"])
print( "    should make capitalized words lowercase", lowercase_formatter.words_to_format(["This"]) == ["this"])
print( "    should make uppercase words lowercase", lowercase_formatter.words_to_format(["THIS"]) == ["this"])
print( "    should join multiple lowercase words with a separator", lowercase_formatter.words_to_format(["this", "thing"]) == ["this ", "thing"])
print( "    should join multiple different cased words with a separator", lowercase_formatter.words_to_format(["this", "thing"]) == ["this ", "thing"])
print( "    should add a separator to previous if they are lacking", lowercase_formatter.words_to_format(["thiS", "THing"], "after") == [" ", "this ", "thing"])
print( "    should handle utf-8 characters by keeping all letters lowercase", lowercase_formatter.words_to_format(["über"]) == ["über"])
print( "    should handle utf-8 characters by making all letters lowercase", lowercase_formatter.words_to_format(["Über"]) == ["über"])
print( "    should handle utf-8 characters by keeping all letters lowercase", lowercase_formatter.words_to_format(["ÜBER"]) == ["über"])

uppercase_formatter = CapitalizationFormatter("upper", " ", CAPITALIZATION_STRATEGY_ALL_CAPS, CAPITALIZATION_STRATEGY_ALL_CAPS)
print( "Upper case formatter with separators" )
print( "    should keep lowercase words uppercase", uppercase_formatter.words_to_format(["this"]) == ["THIS"])
print( "    should make capitalized words uppercase", uppercase_formatter.words_to_format(["This"]) == ["THIS"])
print( "    should keep uppercase words the same", uppercase_formatter.words_to_format(["THIS"]) == ["THIS"])
print( "    should join multiple uppercase words with a separator", uppercase_formatter.words_to_format(["THIS", "THING"]) == ["THIS ", "THING"])
print( "    should join multiple different cased words with a separator", uppercase_formatter.words_to_format(["this", "THING"]) == ["THIS ", "THING"])
print( "    should add a separator to previous if they are lacking", uppercase_formatter.words_to_format(["thiS", "THing"], "after") == [" ", "THIS ", "THING"])
print( "    should handle utf-8 characters by making all letters uppercase", uppercase_formatter.words_to_format(["über"]) == ["ÜBER"])
print( "    should handle utf-8 characters by making all letters uppercase", uppercase_formatter.words_to_format(["Über"]) == ["ÜBER"])
print( "    should handle utf-8 characters by keeping all letters uppercase", uppercase_formatter.words_to_format(["ÜBER"]) == ["ÜBER"])

titlecase_formatters = CapitalizationFormatter("title", " ", CAPITALIZATION_STRATEGY_TITLECASE, CAPITALIZATION_STRATEGY_TITLECASE)
print( "Title case formatter with separators" )
print( "    should keep lower case words capitalized", titlecase_formatters.words_to_format(["this"]) == ["This"])
print( "    should keep capitalized words the same", titlecase_formatters.words_to_format(["This"]) == ["This"])
print( "    should make uppercase words capitalized", titlecase_formatters.words_to_format(["THIS"]) == ["This"])
print( "    should join multiple lowercase words with a separator", titlecase_formatters.words_to_format(["This", "Thing"]) == ["This ", "Thing"])
print( "    should join multiple different cased words with a separator", titlecase_formatters.words_to_format(["this", "THING"]) == ["This ", "Thing"])
print( "    should add a separator to previous if they are lacking", titlecase_formatters.words_to_format(["thiS", "THing"], "after") == [" ", "This ", "Thing"])
print( "    should handle utf-8 characters by making the first letter uppercase", titlecase_formatters.words_to_format(["über"]) == ["Über"])
print( "    should handle utf-8 characters by making the first letter uppercase", titlecase_formatters.words_to_format(["ÜBER"]) == ["Über"])
print( "    should handle utf-8 characters by keeping the first letter uppercase", titlecase_formatters.words_to_format(["ÜBER"]) == ["Über"])

mixed_case_formatting = CapitalizationFormatter("title", "_", CAPITALIZATION_STRATEGY_LOWERCASE, CAPITALIZATION_STRATEGY_TITLECASE)
print( "Mixed case formatting with separators" )
print( "    should keep the first lowercase word the same", mixed_case_formatting.words_to_format(["this"]) == ["this"])
print( "    should make capitalized words lowercase", mixed_case_formatting.words_to_format(["This"]) == ["this"])
print( "    should make uppercase words lowercase", mixed_case_formatting.words_to_format(["THIS"]) == ["this"])
print( "    should make the next lowercase word title case", mixed_case_formatting.words_to_format(["this", "thing"]) == ["this_", "Thing"])
print( "    should keep the next titlecase word title case", mixed_case_formatting.words_to_format(["this", "Thing"]) == ["this_", "Thing"])
print( "    should make the next uppercase word title case", mixed_case_formatting.words_to_format(["this", "THING"]) == ["this_", "Thing"])
print( "    should make the first lowercase word title case if it had a lowercase word before it", mixed_case_formatting.words_to_format(["this", "thing"], "after_") == ["This_", "Thing"])
print( "    should make the first uppercase word title case if it had a lowercase word before it", mixed_case_formatting.words_to_format(["THIS", "thing"], "after_") == ["This_", "Thing"])
print( "    should keep the first titlecase word title case if it had a lowercase word before it", mixed_case_formatting.words_to_format(["This", "thing"], "after_") == ["This_", "Thing"])
print( "    should keep the first lowercase word if it had a non-alphanumeric character before it", mixed_case_formatting.words_to_format(["this", "thing"], "after ") == ["this_", "Thing"])
print( "    should make the first lowercase word title case if it had a non-alphanumeric character before it", mixed_case_formatting.words_to_format(["this", "thing"], "after") == ["_", "This_", "Thing"])

mixed_case_formatting = CapitalizationFormatter("title", "", CAPITALIZATION_STRATEGY_LOWERCASE, CAPITALIZATION_STRATEGY_TITLECASE)
print( "Mixed case formatting without separators" )
print( "    should keep the first lowercase word the same", mixed_case_formatting.words_to_format(["this"]) == ["this"])
print( "    should make capitalized words lowercase", mixed_case_formatting.words_to_format(["This"]) == ["this"])
print( "    should make uppercase words lowercase", mixed_case_formatting.words_to_format(["THIS"]) == ["this"])
print( "    should make the next lowercase word title case", mixed_case_formatting.words_to_format(["this", "thing"]) == ["this", "Thing"])
print( "    should keep the next titlecase word title case", mixed_case_formatting.words_to_format(["this", "Thing"]) == ["this", "Thing"])
print( "    should make the next uppercase word title case", mixed_case_formatting.words_to_format(["this", "THING"]) == ["this", "Thing"])
print( "    should make the first lowercase word title case if it had a lowercase word before it", mixed_case_formatting.words_to_format(["this", "thing"], "after") == ["This", "Thing"])
print( "    should make the first uppercase word title case if it had a lowercase word before it", mixed_case_formatting.words_to_format(["THIS", "thing"], "after") == ["This", "Thing"])
print( "    should keep the first titlecase word title case if it had a lowercase word before it", mixed_case_formatting.words_to_format(["This", "thing"], "after") == ["This", "Thing"])
print( "    should keep the first lowercase word if it had a non-alphanumeric character before it", mixed_case_formatting.words_to_format(["this", "thing"], "after ") == ["this", "Thing"])
